# Generated by Django 4.2.7 on 2026-08-27 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, default='', help_text='Stripe Customer ID (cus_...)', max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', help_text='Stripe Subscription ID (sub_...)', max_length=255)),
                ('plan_name', models.CharField(blank=True, default='free', help_text='Human-readable plan name (e.g. free, pro, enterprise)', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('past_due', 'Past Due')], default='active', max_length=20)),
                ('current_period_end', models.DateTimeField(blank=True, help_text='End of the current billing period (from Stripe)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
